CREATE TABLE ST_TRANSACTION (
    TRANSACTION_ID  VARCHAR(30),
    OPERATION_ID    VARCHAR(30),
    ACCOUNT_ID      BIGINT,
    ACCOUNTING_DATE DATE,
    VALUE_DATE      DATE,
    TYPE            VARCHAR(50),
    AMOUNT          NUMERIC,
    CURRENCY        CHAR(3),
    DESCRIPTION     VARCHAR(140),
    PRIMARY KEY (TRANSACTION_ID)
);